from __future__ import annotations

from copy import deepcopy
from typing import Any


def _choice(level: int, es: str, en: str) -> dict[str, object]:
    return {"level": level, "es": es, "en": en}


def _question(
    number: int,
    kpi: str,
    es: str,
    en: str,
    *choices: tuple[int, str, str],
) -> dict[str, object]:
    return {
        "number": number,
        "kpi": kpi,
        "prompt_es": es,
        "prompt_en": en,
        "choices": [_choice(level, text_es, text_en) for level, text_es, text_en in choices],
    }


INSTRUMENT_VERSION = "2026.07"

# The instrument is the runtime source of truth. The DOCX files are regenerated
# from these records so the respondent-facing wording and the scoring mapping stay aligned.
SMALL_QUESTIONS: list[dict[str, object]] = [
    _question(
        1,
        "Sistema de riego",
        "¿Qué sistema de riego utiliza la empresa?",
        "What irrigation system does the company use?",
        (1, "La empresa usa solo riego por gravedad, sin control de caudal.", "The company uses gravity irrigation only, without flow control."),
        (2, "La empresa combina riego por gravedad y riego presurizado en algunos sectores.", "The company combines gravity and pressurized irrigation in some sectors."),
        (3, "La empresa usa riego presurizado en toda la unidad productiva.", "The company uses pressurized irrigation throughout the production unit."),
    ),
    _question(
        2,
        "Programación de riego",
        "¿Cómo programa la empresa el riego?",
        "How does the company schedule irrigation?",
        (1, "La empresa riega sin horarios definidos.", "The company irrigates without defined schedules."),
        (2, "La empresa usa horarios fijos de riego.", "The company uses fixed irrigation schedules."),
        (3, "La empresa usa herramientas digitales que ajustan el riego según datos del cultivo o del clima.", "The company uses digital tools that adjust irrigation according to crop or weather data."),
    ),
    _question(
        3,
        "Gestión de inventarios",
        "¿Cómo registra la empresa las existencias de insumos y productos?",
        "How does the company record stocks of inputs and products?",
        (1, "La empresa no mantiene un registro organizado de existencias.", "The company does not keep an organized stock record."),
        (2, "La empresa registra las existencias en un cuaderno o una planilla.", "The company records stocks in a notebook or spreadsheet."),
        (3, "La empresa usa un sistema digital para gestionar las existencias.", "The company uses a digital system to manage stocks."),
    ),
    _question(
        4,
        "Cantidad de agua",
        "¿Cómo determina la empresa la cantidad de agua usada para riego?",
        "How does the company determine the amount of water used for irrigation?",
        (1, "La empresa no registra la cantidad de agua aplicada.", "The company does not record the amount of water applied."),
        (2, "La empresa estima el agua usada a partir del tiempo de riego.", "The company estimates water use from irrigation time."),
        (3, "La empresa mide el agua usada con un caudalímetro, es decir, un medidor de agua.", "The company measures water use with a flow meter."),
    ),
    _question(
        5,
        "Sistemas de distribución",
        "¿Cómo se distribuye el agua de riego en el predio?",
        "How is irrigation water distributed on the farm?",
        (1, "El agua se distribuye por canales o mangueras sin una red de tuberías.", "Water is distributed through channels or hoses without a pipe network."),
        (2, "La empresa combina canales o mangueras con tuberías en algunos sectores.", "The company combines channels or hoses with pipes in some sectors."),
        (3, "La empresa distribuye el agua mediante una red de tuberías.", "The company distributes water through a pipe network."),
    ),
    _question(
        6,
        "Producción diaria",
        "¿Cómo registra la empresa la producción diaria?",
        "How does the company record daily production?",
        (1, "La empresa no registra la producción diaria.", "The company does not record daily production."),
        (2, "La empresa registra la producción diaria en cuadernos o planillas.", "The company records daily production in notebooks or spreadsheets."),
        (3, "La empresa usa una herramienta digital para registrar la producción diaria.", "The company uses a digital tool to record daily production."),
    ),
    _question(
        7,
        "Rendimiento",
        "¿Cómo registra la empresa el rendimiento agrícola?",
        "How does the company record agricultural yield?",
        (1, "La empresa no registra el rendimiento.", "The company does not record yield."),
        (2, "La empresa registra el rendimiento en papel.", "The company records yield on paper."),
        (3, "La empresa registra el rendimiento en formato digital.", "The company records yield digitally."),
    ),
    _question(
        8,
        "Comprensión de los estándares de certificación",
        "¿Cuál descripción representa mejor el manejo de requisitos de certificación en la empresa?",
        "Which statement best describes how the company manages certification requirements?",
        (1, "La empresa no identifica requisitos de certificación aplicables.", "The company does not identify applicable certification requirements."),
        (2, "La empresa ha recibido orientación inicial sobre requisitos de certificación.", "The company has received initial guidance on certification requirements."),
        (3, "La empresa conserva evidencia del cumplimiento de requisitos básicos de certificación.", "The company keeps evidence of compliance with basic certification requirements."),
    ),
    _question(
        9,
        "Formación exportadora",
        "¿Cuál es el nivel de formación exportadora del responsable comercial de la empresa?",
        "What is the export-training level of the company's commercial lead?",
        (1, "No ha participado en actividades de formación exportadora.", "They have not participated in export-training activities."),
        (2, "Ha participado en una actividad introductoria sobre exportación.", "They have participated in an introductory export activity."),
        (3, "Ha completado una capacitación aplicada sobre requisitos de exportación.", "They have completed applied training on export requirements."),
    ),
    _question(
        10,
        "Estándares de control de calidad",
        "¿Cuál descripción refleja mejor el control de calidad antes de la venta?",
        "Which statement best reflects quality control before sale?",
        (1, "La empresa no aplica criterios de selección de productos.", "The company does not apply product-selection criteria."),
        (2, "La empresa realiza una revisión visual según los requisitos del comprador.", "The company performs a visual check according to buyer requirements."),
        (3, "La empresa aplica criterios de calidad definidos durante la selección.", "The company applies defined quality criteria during selection."),
    ),
    _question(
        11,
        "Remuneraciones",
        "¿Cómo gestiona la empresa los pagos de remuneraciones?",
        "How does the company manage payroll payments?",
        (1, "La empresa paga remuneraciones en efectivo sin comprobantes ni registros.", "The company pays wages in cash without receipts or records."),
        (2, "La empresa mantiene un registro básico de remuneraciones en papel o formato digital.", "The company keeps a basic payroll record on paper or digitally."),
        (3, "La empresa usa transferencias o un sistema digital para gestionar remuneraciones.", "The company uses transfers or a digital system to manage payroll."),
    ),
    _question(
        12,
        "Fondos concursables",
        "En los últimos tres años, ¿cuál ha sido el mayor nivel de acceso de la empresa a fondos concursables?",
        "In the last three years, what has been the company's highest level of access to competitive funding?",
        (1, "La empresa no ha recibido fondos concursables.", "The company has not received competitive funding."),
        (2, "La empresa ha recibido fondos locales o regionales.", "The company has received local or regional funding."),
        (3, "La empresa ha recibido fondos de alcance nacional.", "The company has received national-level funding."),
    ),
    _question(
        13,
        "Gestión de proveedores",
        "¿Cómo registra la empresa la información de sus proveedores de insumos?",
        "How does the company record information about input suppliers?",
        (1, "La empresa no mantiene un registro organizado de proveedores.", "The company does not keep an organized supplier record."),
        (2, "La empresa usa una planilla digital para registrar proveedores.", "The company uses a digital spreadsheet to record suppliers."),
        (3, "La empresa usa una plataforma para centralizar la información de proveedores.", "The company uses a platform to centralize supplier information."),
    ),
    _question(
        14,
        "Pago de proveedores",
        "¿Cómo registra la empresa los pagos a proveedores?",
        "How does the company record supplier payments?",
        (1, "La empresa realiza pagos en efectivo y los registra en papel.", "The company makes cash payments and records them on paper."),
        (2, "La empresa realiza pagos en efectivo y los registra en formato digital.", "The company makes cash payments and records them digitally."),
        (3, "La empresa realiza pagos por transferencia bancaria.", "The company makes payments by bank transfer."),
    ),
    _question(
        15,
        "Ventas online",
        "¿Cuál es el canal digital de mayor nivel que la empresa utiliza habitualmente para vender?",
        "What is the most advanced digital channel the company regularly uses to sell?",
        (1, "La empresa no usa canales digitales para vender.", "The company does not use digital sales channels."),
        (2, "La empresa usa redes sociales o mensajería para recibir pedidos.", "The company uses social media or messaging to receive orders."),
        (3, "La empresa usa una plataforma de venta con catálogo y pagos en línea.", "The company uses a sales platform with a catalog and online payments."),
    ),
    _question(
        16,
        "Sistemas de pago",
        "¿Cuál es el medio de pago de mayor nivel que la empresa ofrece habitualmente a sus clientes?",
        "What is the most advanced payment method the company regularly offers customers?",
        (1, "La empresa acepta solo pagos en efectivo.", "The company accepts cash payments only."),
        (2, "La empresa acepta transferencias bancarias.", "The company accepts bank transfers."),
        (3, "La empresa usa una plataforma de pago integrada con sus ventas.", "The company uses a payment platform integrated with its sales."),
    ),
    _question(
        17,
        "Nivel educacional",
        "¿Cuál es el nivel más alto de formación del principal tomador de decisiones de la empresa?",
        "What is the highest education level of the company's main decision-maker?",
        (1, "Educación básica o media incompleta.", "Primary education or incomplete secondary education."),
        (2, "Educación media completa o cursos de capacitación sin título técnico.", "Completed secondary education or training courses without a technical degree."),
        (3, "Título técnico o profesional relacionado con agricultura, gestión o administración.", "A technical or professional degree related to agriculture, management, or administration."),
    ),
    _question(
        18,
        "Cumplimiento de roles",
        "¿Cómo asigna la empresa las funciones de trabajo?",
        "How does the company assign work responsibilities?",
        (1, "La empresa no define responsables por función.", "The company does not define a person responsible for each function."),
        (2, "La empresa define algunas responsabilidades, pero no todas.", "The company defines some responsibilities, but not all of them."),
        (3, "La empresa define responsables para las funciones principales.", "The company defines responsible people for its main functions."),
    ),
    _question(
        19,
        "Tecnología On premise",
        "¿Qué uso hace la empresa de software instalado en sus computadores?",
        "How does the company use software installed on its computers?",
        (1, "La empresa no usa software instalado para su gestión.", "The company does not use installed software for management."),
        (2, "La empresa usa software instalado para tareas básicas.", "The company uses installed software for basic tasks."),
        (3, "La empresa usa software instalado para gestionar procesos y recibe soporte remoto básico.", "The company uses installed software to manage processes and receives basic remote support."),
    ),
    _question(
        20,
        "Iniciativas de formación",
        "¿Con qué frecuencia la empresa realiza actividades de capacitación técnica?",
        "How often does the company conduct technical-training activities?",
        (1, "La empresa no realiza actividades de capacitación técnica.", "The company does not conduct technical-training activities."),
        (2, "La empresa participa ocasionalmente en talleres o capacitaciones.", "The company occasionally participates in workshops or training."),
        (3, "La empresa realiza capacitaciones con una periodicidad planificada.", "The company conducts training on a planned schedule."),
    ),
    _question(
        21,
        "Soporte técnico",
        "¿Con qué frecuencia la empresa recibe apoyo técnico especializado?",
        "How often does the company receive specialized technical support?",
        (1, "La empresa no recibe apoyo técnico.", "The company does not receive technical support."),
        (2, "La empresa recibe apoyo técnico ocasional o general.", "The company receives occasional or general technical support."),
        (3, "La empresa recibe apoyo técnico especializado de forma regular.", "The company receives specialized technical support regularly."),
    ),
]


MEDIUM_QUESTIONS: list[dict[str, object]] = [
    _question(
        1,
        "Sistema de riego",
        "¿Qué sistema de riego utiliza la empresa?",
        "What irrigation system does the company use?",
        (1, "La empresa usa solo riego por gravedad, sin control de caudal.", "The company uses gravity irrigation only, without flow control."),
        (2, "La empresa combina riego por gravedad y riego presurizado en algunos sectores.", "The company combines gravity and pressurized irrigation in some sectors."),
        (3, "La empresa usa riego presurizado con control de presión y caudal.", "The company uses pressurized irrigation with pressure and flow control."),
        (4, "La empresa usa riego presurizado que ajusta el consumo de agua con datos de sensores.", "The company uses pressurized irrigation that adjusts water use with sensor data."),
    ),
    _question(
        2,
        "Programación de riego",
        "¿Cómo programa la empresa el riego?",
        "How does the company schedule irrigation?",
        (1, "La empresa riega sin horarios definidos.", "The company irrigates without defined schedules."),
        (2, "La empresa usa horarios fijos de riego.", "The company uses fixed irrigation schedules."),
        (3, "La empresa usa temporizadores o controladores que activan el riego automáticamente.", "The company uses timers or controllers that activate irrigation automatically."),
        (4, "La empresa ajusta el riego con datos de sensores y del clima en tiempo real.", "The company adjusts irrigation with real-time sensor and weather data."),
    ),
    _question(
        3,
        "Gestión de inventarios",
        "¿Cómo registra la empresa las existencias de insumos, herramientas y productos?",
        "How does the company record stocks of inputs, tools, and products?",
        (1, "La empresa no usa un registro digital de existencias.", "The company does not use a digital stock record."),
        (2, "La empresa registra las existencias en una planilla digital.", "The company records stocks in a digital spreadsheet."),
        (3, "La empresa usa software especializado para gestionar existencias.", "The company uses specialized software to manage stocks."),
        (4, "La empresa usa una plataforma que actualiza existencias y genera reportes.", "The company uses a platform that updates stocks and generates reports."),
    ),
    _question(
        4,
        "Cantidad de agua",
        "¿Cómo determina la empresa la cantidad de agua usada para riego?",
        "How does the company determine the amount of water used for irrigation?",
        (1, "La empresa no registra el tiempo de riego.", "The company does not record irrigation time."),
        (2, "La empresa registra las horas de riego.", "The company records irrigation hours."),
        (3, "La empresa estima el volumen de agua con las horas de riego y el caudal.", "The company estimates water volume using irrigation hours and flow rate."),
        (4, "La empresa mide el volumen de agua con un caudalímetro, es decir, un medidor de agua.", "The company measures water volume with a flow meter."),
    ),
    _question(
        5,
        "Sistemas de distribución",
        "¿Cómo se distribuye el agua de riego en el predio?",
        "How is irrigation water distributed on the farm?",
        (1, "El agua se distribuye sin un sistema definido.", "Water is distributed without a defined system."),
        (2, "La empresa combina canales o mangueras con algunas tuberías.", "The company combines channels or hoses with some pipes."),
        (3, "La empresa distribuye el agua mediante una red de tuberías.", "The company distributes water through a pipe network."),
        (4, "La empresa usa una red de tuberías con controladores computarizados.", "The company uses a pipe network with computerized controllers."),
    ),
    _question(
        6,
        "Producción diaria",
        "¿Cuál descripción representa mejor la gestión de la producción diaria?",
        "Which statement best describes daily-production management?",
        (1, "La empresa registra la producción diaria de forma manual.", "The company records daily production manually."),
        (2, "La empresa usa software para planificar la producción diaria.", "The company uses software to plan daily production."),
        (3, "La empresa usa software que genera indicadores para ajustar la planificación.", "The company uses software that generates indicators to adjust planning."),
        (4, "La empresa usa herramientas de inteligencia artificial para proponer ajustes de producción.", "The company uses artificial-intelligence tools to propose production adjustments."),
    ),
    _question(
        7,
        "Rendimiento",
        "¿Cómo registra la empresa el rendimiento agrícola?",
        "How does the company record agricultural yield?",
        (1, "La empresa no registra el rendimiento.", "The company does not record yield."),
        (2, "La empresa registra el rendimiento en papel.", "The company records yield on paper."),
        (3, "La empresa registra el rendimiento en formato digital.", "The company records yield digitally."),
        (4, "La empresa registra el rendimiento de forma automática.", "The company records yield automatically."),
    ),
    _question(
        8,
        "Comprensión de los estándares de certificación",
        "¿Cuál descripción representa mejor el estado de certificación de la empresa?",
        "Which statement best describes the company's certification status?",
        (1, "La empresa no identifica requisitos de certificación aplicables.", "The company does not identify applicable certification requirements."),
        (2, "La empresa ha recibido capacitación inicial sobre requisitos de certificación.", "The company has received initial training on certification requirements."),
        (3, "La empresa aplica requisitos nacionales de certificación y conserva evidencia de cumplimiento.", "The company applies national certification requirements and keeps evidence of compliance."),
        (4, "La empresa cuenta con una certificación internacional vigente.", "The company holds a current international certification."),
    ),
    _question(
        9,
        "Formación exportadora",
        "¿Cuál es el nivel de formación exportadora del responsable comercial de la empresa?",
        "What is the export-training level of the company's commercial lead?",
        (1, "No ha participado en actividades de formación exportadora.", "They have not participated in export-training activities."),
        (2, "Ha participado en una actividad introductoria sobre exportación.", "They have participated in an introductory export activity."),
        (3, "Ha completado una capacitación aplicada sobre requisitos de exportación.", "They have completed applied training on export requirements."),
        (4, "Se actualiza regularmente en mercados y regulaciones internacionales.", "They update their knowledge of international markets and regulations regularly."),
    ),
    _question(
        10,
        "Estándares de control de calidad",
        "¿Cuál descripción refleja mejor el control de calidad antes de la venta?",
        "Which statement best reflects quality control before sale?",
        (1, "La empresa no aplica criterios de selección de productos.", "The company does not apply product-selection criteria."),
        (2, "La empresa realiza una revisión visual según los requisitos del comprador.", "The company performs a visual check according to buyer requirements."),
        (3, "La empresa registra controles de calidad y aplica criterios definidos.", "The company records quality controls and applies defined criteria."),
        (4, "La empresa realiza auditorías de calidad para cumplir estándares internacionales.", "The company performs quality audits to meet international standards."),
    ),
    _question(
        11,
        "Remuneraciones",
        "¿Cómo gestiona la empresa los pagos de remuneraciones?",
        "How does the company manage payroll payments?",
        (1, "La empresa paga remuneraciones en efectivo sin comprobantes ni registros.", "The company pays wages in cash without receipts or records."),
        (2, "La empresa mantiene un registro básico de remuneraciones en papel o formato digital.", "The company keeps a basic payroll record on paper or digitally."),
        (3, "La empresa usa software para gestionar remuneraciones y generar reportes.", "The company uses software to manage payroll and generate reports."),
        (4, "La empresa usa un sistema integrado con bancos y plataformas contables.", "The company uses a system integrated with banks and accounting platforms."),
    ),
    _question(
        12,
        "Fondos concursables",
        "En los últimos tres años, ¿cuál ha sido el mayor nivel de acceso de la empresa a fondos concursables?",
        "In the last three years, what has been the company's highest level of access to competitive funding?",
        (1, "La empresa no ha recibido fondos concursables.", "The company has not received competitive funding."),
        (2, "La empresa ha recibido fondos locales o regionales de monto acotado.", "The company has received limited local or regional funding."),
        (4, "La empresa ha recibido fondos concursables de alcance nacional o asociativo.", "The company has received national or collaborative competitive funding."),
    ),
    _question(
        13,
        "Gestión de proveedores",
        "¿Cómo registra la empresa la información de sus proveedores de insumos?",
        "How does the company record information about input suppliers?",
        (1, "La empresa registra a sus proveedores de manera manual.", "The company records suppliers manually."),
        (2, "La empresa usa una planilla o una aplicación básica para registrar proveedores.", "The company uses a spreadsheet or a basic application to record suppliers."),
        (3, "La empresa usa una plataforma para hacer seguimiento de proveedores y compras.", "The company uses a platform to track suppliers and purchases."),
        (4, "La empresa integra a sus proveedores en un sistema de gestión.", "The company integrates suppliers into a management system."),
    ),
    _question(
        14,
        "Pago de proveedores",
        "¿Cómo gestiona la empresa los pagos a proveedores?",
        "How does the company manage supplier payments?",
        (1, "La empresa no mantiene registros de pagos a proveedores.", "The company does not keep records of supplier payments."),
        (2, "La empresa realiza pagos digitales con registros básicos.", "The company makes digital payments with basic records."),
        (3, "La empresa usa software para integrar pagos y compras.", "The company uses software to integrate payments and purchases."),
        (4, "La empresa automatiza pagos mediante su sistema contable o de gestión.", "The company automates payments through its accounting or management system."),
    ),
    _question(
        15,
        "Ventas online",
        "¿Cuál es el canal digital de mayor nivel que la empresa utiliza habitualmente para vender?",
        "What is the most advanced digital channel the company regularly uses to sell?",
        (1, "La empresa no usa canales digitales para vender.", "The company does not use digital sales channels."),
        (2, "La empresa usa redes sociales o mensajería para recibir pedidos.", "The company uses social media or messaging to receive orders."),
        (3, "La empresa usa una plataforma de venta con catálogo y pagos en línea.", "The company uses a sales platform with a catalog and online payments."),
        (4, "La empresa usa comercio electrónico integrado con logística digital.", "The company uses e-commerce integrated with digital logistics."),
    ),
    _question(
        16,
        "Sistemas de pago",
        "¿Cuál descripción refleja mejor la gestión de los pagos de clientes?",
        "Which statement best reflects the management of customer payments?",
        (1, "La empresa acepta pagos en efectivo y los registra en papel.", "The company accepts cash payments and records them on paper."),
        (2, "La empresa acepta pagos en efectivo y los registra en formato digital.", "The company accepts cash payments and records them digitally."),
        (3, "La empresa procesa transferencias bancarias de forma automatizada.", "The company processes bank transfers automatically."),
        (4, "La empresa centraliza los pagos en un sistema de gestión empresarial.", "The company centralizes payments in a business-management system."),
    ),
    _question(
        17,
        "Nivel educacional",
        "¿Cuál es el nivel más alto de formación del principal tomador de decisiones de la empresa?",
        "What is the highest education level of the company's main decision-maker?",
        (1, "Experiencia práctica o educación media incompleta.", "Practical experience or incomplete secondary education."),
        (2, "Formación técnica o cursos especializados.", "Technical training or specialized courses."),
        (3, "Título universitario en gestión, agronomía o administración.", "A university degree in management, agronomy, or administration."),
        (4, "Postgrado o especialización avanzada en un área relevante.", "A postgraduate degree or advanced specialization in a relevant area."),
    ),
    _question(
        18,
        "Cumplimiento de roles",
        "¿Cómo están definidos los roles dentro de la empresa?",
        "How are roles defined within the company?",
        (1, "Las responsabilidades cambian según la necesidad y no están definidas.", "Responsibilities change as needed and are not defined."),
        (2, "La empresa ha definido algunas responsabilidades, pero no en todas las áreas.", "The company has defined some responsibilities, but not in every area."),
        (3, "La empresa define responsables para las funciones principales.", "The company defines responsible people for its main functions."),
        (4, "Las áreas de la empresa cuentan con roles especializados.", "The company's areas have specialized roles."),
    ),
    _question(
        19,
        "Tecnología Cloud",
        "¿Dónde almacena y comparte la empresa su información de gestión?",
        "Where does the company store and share its management information?",
        (1, "La empresa no usa infraestructura digital de gestión de forma regular.", "The company does not regularly use digital management infrastructure."),
        (2, "La empresa usa un servidor o computador local para centralizar información.", "The company uses a local server or computer to centralize information."),
        (3, "La empresa combina un sistema local con servicios en la nube.", "The company combines a local system with cloud services."),
        (4, "La empresa usa infraestructura en la nube integrada para su gestión.", "The company uses integrated cloud infrastructure for management."),
    ),
    _question(
        20,
        "Tecnología On premise",
        "¿Cuál descripción representa mejor el software de gestión que utiliza la empresa?",
        "Which statement best describes the management software the company uses?",
        (1, "La empresa depende de registros manuales para su gestión.", "The company relies on manual records for management."),
        (2, "La empresa usa software básico instalado en sus equipos.", "The company uses basic software installed on its equipment."),
        (3, "La empresa usa software local con apoyo de herramientas en la nube.", "The company uses local software supported by cloud tools."),
        (4, "La empresa usa sistemas de gestión integrados en la nube.", "The company uses integrated cloud-based management systems."),
    ),
    _question(
        21,
        "Iniciativas de formación",
        "¿Cómo organiza la empresa la formación técnica de su equipo?",
        "How does the company organize technical training for its team?",
        (1, "La empresa no realiza actividades de capacitación técnica.", "The company does not conduct technical-training activities."),
        (2, "La empresa participa ocasionalmente en talleres externos.", "The company occasionally participates in external workshops."),
        (3, "La empresa aplica un plan de formación continua.", "The company implements a continuous training plan."),
        (4, "La empresa evalúa y ajusta su estrategia de formación.", "The company evaluates and adjusts its training strategy."),
    ),
    _question(
        22,
        "Soporte técnico",
        "¿Con qué frecuencia la empresa recibe apoyo técnico especializado?",
        "How often does the company receive specialized technical support?",
        (1, "La empresa no recibe apoyo técnico.", "The company does not receive technical support."),
        (2, "La empresa recibe apoyo técnico ocasional o general.", "The company receives occasional or general technical support."),
        (3, "La empresa recibe apoyo técnico especializado en algunas áreas.", "The company receives specialized technical support in some areas."),
        (4, "La empresa recibe apoyo técnico especializado en todas las áreas principales.", "The company receives specialized technical support in all main areas."),
    ),
]


_INSTRUMENTS = {"small": SMALL_QUESTIONS, "medium": MEDIUM_QUESTIONS}


def get_questionnaire(profile: str) -> list[dict[str, Any]]:
    if profile not in _INSTRUMENTS:
        raise ValueError("company type must be small or medium")
    return deepcopy(_INSTRUMENTS[profile])
